### ISSUE TITLE
Stress scrolling breaks proper image sizing

### ISSUE THREAD

**Issue by Javernaut** [saulmm/CoordinatorLayoutExample#3]
Hello.
If you will make some stress scrolling of this screen, you can get several different states where image isn't resized and placed properly. See an example. I use Samsung S4 with GearCM12.1.
![screenshot_2015-08-25-15-42-39](https://cloud.githubusercontent.com/assets/979018/9466817/30bd520c-4b40-11e5-89e3-52f17ff43ad5.png)

**Comment by Javernaut** [comment]
Or such one:
![screenshot_2015-08-25-15-48-33](https://cloud.githubusercontent.com/assets/979018/9466927/d3a00a5a-4b40-11e5-936e-aa5a4a892265.png)

**Comment by saulmm** [comment]
There were a lot of hardcoded values, I've updated them at d9226cb, Could you try again?
